services:
  ngircd:
    build:
      context: ./ngircd
    ports:
      - "6667:6667"
    networks:
      - mynetwork
  bot:
    build:
      context: ./bot
    depends_on:
      - ngircd
    networks:
      - mynetwork
    environment:
      - PYTHONUNBUFFERED=1

networks:
  mynetwork:
    driver: bridge
